### ISSUE TITLE
OutOfMemoryError when using parquet->ds-seq

### ISSUE THREAD

**Issue by alza-bitz** [techascent/tech.parquet#2]
Hi,

I'm trying to stream a ~300MB parquet file at the REPL using `tech.v3.libs.parquet/parquet->ds-seq` but I get `java.lang.OutOfMemoryError: Java heap space` in each case:

```
(-> "large.snappy.parquet"
      parquet/parquet->ds-seq
      first)
```

```
(-> "large.snappy.parquet"
      parquet/parquet->ds-seq
      count)
```

```
(-> "large.snappy.parquet"
      parquet/parquet->ds-seq
      realized?)
```

Reading the metadata does work, however:

```
(-> "large.snappy.parquet"
      parquet/parquet->metadata-seq)
```

I had a quick look at the code for `parquet->ds-seq`, it seems to be using lazy seqs so is there anything I'm doing wrong on my side to stream the data through correctly and avoid `java.lang.OutOfMemoryError`?

**Comment by cnuernber** [comment]
I think everything you are doing is right and there is an issue with the actual parquet parsing code where each block isn't being released correctly.  

If it helps the arrow system will both read and write very large sequences of datasets and it contains both lz4 and zstd per-column compression.

If not this is absolutely a legitimate issue we need to look at - I have generated the same error recently.

**Comment by alza-bitz** [comment]
Hi there,

> I think everything you are doing is right and there is an issue with the actual parquet parsing code where each block isn't being released correctly.

Ok, have you got a reference for this as a Github issue on the Parquet side that I could look at?

> If it helps the arrow system will both read and write very large sequences of datasets and it contains both lz4 and zstd per-column compression.

Could you explain what you mean by "arrow system", and maybe give an example?

Thanks!

**Comment by cnuernber** [comment]
1. - there is no TMD issue on this - this issue is fine for reference for now.
2. - https://techascent.github.io/tech.ml.dataset/tech.v3.libs.arrow.html - that has examples - we tested it with quite large sequences of datasets and it worked fine and was faster than a duckdb read for a simple scan (and much faster for write).

**Comment by cnuernber** [comment]
The newest release - 7.028 of TMD does load large parquet files without OOM.  The issue is that it is fairly slow as we can't parallelize the decoding of parquet columns due to internal issues in the parquet library.  For this reason - again - we recommend using arrow with zstd compression.  The compression isn't quite as good but in one of our tests a 2.5GB compressed dataset loaded with parquet in 127 seconds while with arrow it loaded in under 7 seconds.
